language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install flake8 pylint coveralls
script:
  - flake8 homeassistant --exclude bower_components,external
  - pylint homeassistant
  - coverage run --source=homeassistant -m unittest discover test
after_success:
  - coveralls
